server:
  port: 8380
capi:
  #### Kafka is still experimental ####
  kafka:
    enabled: false
    host: localhost:9092
  reverse:
    proxy:
      enabled: false
      host: localhost:8380
  #### DO NOT CHANGE, unless you know exactly that you CAPI to follow Redirects. ###
  #### If you want to disable routes from following redirects ####
  disable:
    redirect: true
  #### Websocket Gateway (Editable Property) ####
  websocket:
    enabled: false
    server:
      host: localhost
      port: 8381
  #### Enable Zipkin (Editable Property) ####
  zipkin:
    enabled: false
    endpoint: http://localhost:9411/api/v2/spans
  #### Consul Integration (Editable Property) ####
  #### If you want CAPI to search consul for available APIs to be deployed, enable this feature. ####
  consul:
    host: http://localhost:8500
    discovery:
      enabled: false
      timer:
        interval: 10000
  #### Certificate Management (Editable property) ####
  #### If you want to enable certificate management, please provide a trust store (JKS). ####
  trust:
    store:
      enabled: false
      path:
      password:
  #### CORS (Manager) (Editable property)
  #### For web applications calling CAPI Manager Endpoint, if you want to restrict who is allowed to call.
  manager:
    cors:
      host: http://localhost:4200
    #### Management endpoints security configuration (Editable property) ####
    ## CAPI Manager endpoints can be secured by enabling this feature, if you enable, you need to provide the JWK endpoint of your OIDC provider.
    ## If the OIDC Provider listens on HTTPS, it needs to be trusted by CAPI
    security:
      enabled: false
      issuer:
  #### Persistence Management ####
  persistence:
    enabled: false
  db:
    discovery:
      timer:
        interval: 40000
  version: ^project.version^
  name: ^project.name^
  spring:
    version: ^project.description^
  gateway:
    error:
      #### All calls in error will be bridged to this endpoint ####
      endpoint: localhost:8380/capi-error

#### DO NOT CHANGE SPRINGDOC PROPERTIES ####
#### This is important to disable the default petstore ####
springdoc:
  swagger-ui:
    enabled: true
    disable.swagger-default-url: true
#### DO NOT CHANGE THESE SPRING AUTOCONFIGURE EXCLUSIONS #####
spring:
  #### We want persistence to be optional, so we disable autoconfiguration for JPA ####
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  ### JDBC Properties (default MySQL) (Editable) ###
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/capi
    username: root
    password: root
  profiles:
    active: default
  ### CAPI Banner, keep it, it is beautiful!
  banner:
    location: classpath:capi.txt
  ### Allow bean definition overriding (Do not change) ###
  main:
    allow-bean-definition-overriding: true
camel:
  component:
    metrics:
      enabled: true
  servlet:
    mapping:
      context-path: /capi/*
  springboot:
    name: capi-gateway

#### SSL Configuration ####
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=/Users/rodrigo/ext/gsc/capi-lb.p12
#server.ssl.key-store-password=capi-lb
#server.ssl.key-alias=capi-lb
#server.ssl.enabled=true


#### Actuator Metrics Endpoint Configuration (Do not change) ####
management:
  security:
    enabled: false
  endpoint:
    camelroutes:
      enabled: true
  endpoints:
    web:
      base-path: /analytics/
      exposure:
        include: 'health,prometheus'

#### Time to live for Sticky Sessions feature ####
sticky:
  session:
    time:
      to:
        live: 2
#### OAUTH2 Support to protect the routes. (Editable properties) ####
oidc:
  cookieName:
  provider:
    enabled: false
    keys: http://localhost:8080/realms/master/protocol/openid-connect/certs
    host: http://localhost:8080
    realm: /realms/master
    clientId:
    clientSecret: