name: CAPI-LB
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 21
    - uses: actions/checkout@v3.5.3
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v21
    - name: Set Release version env variable
      run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn package -DskipTests --file pom.xml
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Build Inventory Image'
      run: |
         docker build . --tag ghcr.io/surisoft-io/capi:${{ env.RELEASE_VERSION }}
         docker push ghcr.io/surisoft-io/capi:${{ env.RELEASE_VERSION }}
